# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    anuncios_directory: '%kernel.project_dir%/public/uploads/anuncios'
    tablets_directory: '%kernel.project_dir%/public/uploads/tablets'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Services\FileUploader:
        arguments:
            $targetDirectory: '%anuncios_directory%'
            $targetDirectoryCorp: '%tablets_directory%'


    App\BLL\BaseBLL:
        abstract: true
        autowire: false
        autoconfigure: false
        calls:
            - method: setEntityManager
              arguments:
                  - '@doctrine.orm.default_entity_manager'
            - method: setValidator
              arguments:
                  - '@validator'
            - method: setTokenStorage
              arguments:
                  - '@security.token_storage'
            - method: setParameterBag
              arguments:
                  - '@parameter_bag'

    App\BLL\AnuncioBLL:
        autowire: false
        autoconfigure: false
        public: false
        parent: App\BLL\BaseBLL

    App\BLL\ReproduccionBLL:
        autowire: false
        autoconfigure: false
        public: false
        parent: App\BLL\BaseBLL

    App\BLL\ServicioBLL:
        autowire: false
        autoconfigure: false
        public: false
        parent: App\BLL\BaseBLL

    App\BLL\UsuarioBLL:
        autowire: false
        autoconfigure: false
        public: false
        parent: App\BLL\BaseBLL
        calls:
            - method: setEncoder
              arguments:
                  - '@security.user_password_encoder.generic'
            - method: setJWTManager
              arguments:
                  - '@lexik_jwt_authentication.jwt_manager'
    App\BLL\OneSignalBLL:
        autowire: false
        autoconfigure: false
        public: false
        parent: App\BLL\BaseBLL